name: PR Lint

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Placeholder lint
        run: |
          echo "[CI] Lint placeholder. Later add ktlint/detekt invocation"
